# Generated by Django 3.1.6 on 2021-02-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, default='walle.jpg', upload_to=''),
        ),
    ]
